trigger:
- main

pool:
  name: Armonden

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: 'Restore .NET packages'
  inputs:
    targetType: 'inline'
    script: 'dotnet restore'

- task: Bash@3
  displayName: 'Download CSS assets'
  inputs:
    targetType: 'inline'
    script: 'wget https://robertmonden.com/files/build/rm_portfolio_assets.zip --secure-protocol=TLSv1 -P RobertMonden.Website/wwwroot/css'

- task: Bash@3
  displayName: 'Extract CSS assets'
  inputs:
    targetType: 'inline'
    script: 'unzip RobertMonden.Website/wwwroot/css/rm_portfolio_assets.zip -d RobertMonden.Website/wwwroot/css'

- task: Bash@3
  displayName: 'Create production build'
  inputs:
    filePath: './publish.sh'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'