trigger:
- main

pool:
  name: Armonden

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: 'Restore .NET packages'
  inputs:
    targetType: 'inline'
    script: 'dotnet restore'
- task: Bash@3
  displayName: 'Build project'
  inputs:
    targetType: 'inline'
    script: 'dotnet build'
